name: lint & test & coverage
on:
  push:
    branches:
      - main
jobs:
  lint:
    name: lint
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node: [ '12' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@main
      - uses: actions/checkout@main
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run lint:js
  test:
    needs: [ lint ]
    name: test
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node: [ '12' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@main
      - uses: actions/checkout@main
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run test
  coverage:
    needs: [ lint, test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@main
      - uses: actions/checkout@main
        with:
          node-version: '12'
      - run: npm install
      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage
